### ISSUE TITLE
求助老哥帮忙看看这个

### ISSUE THREAD

**Issue by deemoartisan** [jw-star/91pornBot#11]
File "/www/wwwroot/91bot/91pornBot-mas/pornbot.py", line 28, in <module>
    REDIS_PORT = int(os.getenv(6379))
  File "/usr/lib/python3.9/os.py", line 775, in getenv
    return environ.get(key, default)
  File "/usr/lib/python3.9/_collections_abc.py", line 762, in get
    return self[key]
  File "/usr/lib/python3.9/os.py", line 676, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int

**Comment by jw-star** [comment]
检查 REDIS_PORT 填写内容

**Comment by jw-star** [comment]
如果你在本地启动，不是docker，自己把从环境变量获取的更改下

**Comment by deemoartisan** [comment]
整体配置我是这样的：
REDIS_HOST = os.getenv('127.0.0.1')
REDIS_PORT = int(os.getenv(6379))
REDIS_PASS = os.getenv(1234567)
API_ID = int(os.getenv(12952264))
API_HASH = os.getenv('28fddff27a9ecb1c820b45130b27aab1')
BOT_TOKEN = os.getenv('5361594604:AAGMOcc4kOGU-BvKPw9aAnuLTuNtjmxXsS0')
GROUP_ID = int(os.getenv(1001313663361))
bot = TelegramClient(None, API_ID, API_HASH,
                     # proxy=(socks.HTTP, '127.0.0.1', 10809)
                     ).start(
    bot_token=BOT_TOKEN)
redis_conn = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, password=REDIS_PASS, db=1, decode_responses=True)



按理来说，我直接用宝塔装的redis，端口显示就是6379，我就按这个填上去了

**Comment by jw-star** [comment]
os.getenv 是从环境变量获取，你把这几个全都去了
比如： 
```
REDIS_HOST = '127.0.0.1'

REDIS_PORT = int(6379)
```

**Comment by jw-star** [comment]
另外你还需要安装ffmpeg，chromedriver到linux中

**Comment by deemoartisan** [comment]
机器人活过来了，发送链接提示“请设置用户名后再发送链接”

简单排查了一下，比如机器人的设置和网站里的登录情况也正常

这个是啥情况呀老哥

**Comment by jw-star** [comment]
刚提交去了那一段代码，你看下

**Comment by deemoartisan** [comment]
你这。。。。确实牛B
