### ISSUE TITLE
跑起了， 也可以解析下载了， 但是没有发送到指定群呢？ 

### ISSUE THREAD

**Issue by mobilelifeful** [jw-star/91pornBot#16]
假如群为：
https://web.telegram.org/z/#-156708669X

这样填对吗？

      #windows配置环境变量需要重启电脑
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASS:  
      API_ID: 我的API
      API_HASH: 我的API_HASH
      BOT_TOKEN: 机器人的
      #定时任务发送的群组id(@get_id_bot,可以在这里获取到)
      GROUP_ID: 156708669X
      

      CRON_HOUR_91: 1  #定时任务开始的小时（24小时制） 
      CRON_MINUTE_91: 50 #定时任务开始的分（<60）

CRON_HOUR_91 和 CRON_MINUTE_91  是否就是上海时间 1 点50分 发到156708669X里？
就想想测试下， 是否可以成功发送到群内，        
       谢谢

**Comment by jw-star** [comment]
GROUP_ID 带上    -100,用群身份发消息后转发给 @get_id_bot，也可以查看      -100156xxx

**Comment by jw-star** [comment]
请修改linux的时区，docker会同步linux上的时区文件
