### ISSUE TITLE
报错：UnhandLed exception on echo all 如何解决?

### ISSUE THREAD

**Issue by shangdev** [jw-star/91pornBot#17]
![image](https://user-images.githubusercontent.com/15621520/209606005-320c9993-300b-479a-b75e-bd8b06df4ff1.png)

**Comment by jw-star** [comment]
https://github.com/jw-star/91pornBot/blob/c4c8723c015406c676a1c8263573874349d55969/pornbot.py#L163

这一部分截图 问题，改成截取第一帧视频可以先，截取网址的有时候有问题

**Comment by jw-star** [comment]
改了，重新拉一下镜像试试

**Comment by shangdev** [comment]
![image](https://user-images.githubusercontent.com/15621520/209632628-a303b8b7-9727-4f43-bb4e-626b477833e9.png)

重新拉了镜像。可以发送下载后的视频给机器人，但是没发送到docker-compose.yml中定义的GROUP_ID群组中，正常吗？

和截图中那个 “自定应词典不存在” 有关系吗？

**Comment by jw-star** [comment]
定时任务每天爬取首页才发送到群组

**Comment by jw-star** [comment]
https://github.com/jw-star/91pornBot/tree/mas/config  你需要把config目录放到docker-compose.yml 同目录，才可以读取到词典

**Comment by shangdev** [comment]
赞一个
