### ISSUE TITLE
可以给docker添加代理选项吗？

### ISSUE THREAD

**Issue by zzzop** [jw-star/91pornBot#18]
想不买服务器本地部署

**Comment by jw-star** [comment]
本地部署的话，不稳定，还得装docker，你可以在vultr上买个新加坡服务器，一个月30元

**Comment by jw-star** [comment]
![image](https://user-images.githubusercontent.com/48782751/211179354-e00c3f96-eeb2-41ce-9f43-f4766bd6d3e1.png)
