### ISSUE TITLE
机器人发送视频尺寸问题

### ISSUE THREAD

**Issue by IKIVIY** [jw-star/91pornBot#2]

**Comment by jw-star** [comment]
> 发送的视频尺寸被拉伸，能不能优化一下

视频读取的是原来的尺寸，有具体的例子吗，发我看下

**Comment by IKIVIY** [comment]
你的tg号发给我

**Comment by IKIVIY** [comment]
> > 发送的视频尺寸被拉伸，能不能优化一下
> 
> 
> 
> 视频读取的是原来的尺寸，有具体的例子吗，发我看下

你tg号发给我 我给你看下

**Comment by jw-star** [comment]
> > > 发送的视频尺寸被拉伸，能不能优化一下
> > 
> > 
> > 视频读取的是原来的尺寸，有具体的例子吗，发我看下
> 
> 你tg号发给我 我给你看下

群里说话

**Comment by IKIVIY** [comment]
我不知道群 是那个？发给我一下> > > > 发送的视频尺寸被拉伸，能不能优化一下
> 
> > > 
> 
> > > 
> 
> > > 视频读取的是原来的尺寸，有具体的例子吗，发我看下
> 
> > 
> 
> > 你tg号发给我 我给你看下
> 
> 
> 
> 群里说话

**Comment by IKIVIY** [comment]
> > > > 发送的视频尺寸被拉伸，能不能优化一下
> 
> > > 
> 
> > > 
> 
> > > 视频读取的是原来的尺寸，有具体的例子吗，发我看下
> 
> > 
> 
> > 你tg号发给我 我给你看下
> 
> 
> 
> 群里说话

群号能说一下么

**Comment by jw-star** [comment]
> > > > > 发送的视频尺寸被拉伸，能不能优化一下
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 视频读取的是原来的尺寸，有具体的例子吗，发我看下
> > 
> > 
> > > 
> > 
> > 
> > > 你tg号发给我 我给你看下
> > 
> > 
> > 群里说话
> 
> 群号能说一下么

还是加我吧，@bzhzq
