### ISSUE TITLE
这一段怎么写

### ISSUE THREAD

**Issue by seagullz4** [jw-star/91pornBot#22]
REDIS_HOST: 11.11.22.333
      REDIS_PORT: 16379
      REDIS_PASS: 424243

**Comment by jw-star** [comment]
redis配置，看docker-compose.yml

**Comment by jw-star** [comment]
![image](https://user-images.githubusercontent.com/48782751/229012471-ec6ce47b-4b60-4192-a7c6-5bc8a11bde00.png)
