### ISSUE TITLE
能把Python版放出来吗？

### ISSUE THREAD

**Issue by aq859142062** [jw-star/91pornBot#4]
能把Python版放出来吗？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jw-star** [comment]
> 能把Python版放出来吗？
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

暂时不放了，思路和java的差不多

**Comment by jw-star** [comment]
> 能把Python版放出来吗？
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

参考 这个  https://github.com/jw-star/pornbot91_py

**Comment by mobilelifeful** [comment]
@aq859142062  这个项目 没有开源吗？
