### ISSUE TITLE
这个报错怎么办

### ISSUE THREAD

**Issue by aq859142062** [jw-star/91pornBot#6]
Traceback (most recent call last):
  File "pornbot.py", line 33, in <module>
    REDIS_PORT = int(os.getenv('REDIS_PORT'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jw-star** [comment]
> Traceback (most recent call last): File "pornbot.py", line 33, in REDIS_PORT = int(os.getenv('REDIS_PORT')) TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

端口号是数字，不要填字符串

**Comment by aq859142062** [comment]
在哪填端口号啊？

**Comment by aq859142062** [comment]
> > Traceback (most recent call last): File "pornbot.py", line 33, in REDIS_PORT = int(os.getenv('REDIS_PORT')) TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> > Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)
> 
> 端口号是数字，不要填字符串，本地启动的话，请自行替换环境变量，不要用os获取

在哪填端口号啊？

**Comment by aq859142062** [comment]
> > Traceback (most recent call last): File "pornbot.py", line 33, in REDIS_PORT = int(os.getenv('REDIS_PORT')) TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> > Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)
> 
> 端口号是数字，不要填字符串，本地启动的话，请自行替换环境变量，不要用os获取

我用docker出错 总是下载失败 成功了机器人也不发消息

**Comment by jw-star** [comment]
> > > Traceback (most recent call last): File "pornbot.py", line 33, in REDIS_PORT = int(os.getenv('REDIS_PORT')) TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> > > Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)
> > 
> > 
> > 端口号是数字，不要填字符串，本地启动的话，请自行替换环境变量，不要用os获取
> 
> 我用docker出错 总是下载失败 成功了机器人也不发消息

@nbxbhj，电报私聊吧，这样回复太慢了
